FROM centos:6

RUN rm /etc/yum.repos.d/* /etc/pki/rpm-gpg/*
# From https://www.getpagespeed.com/files/centos6-eol.repo
# From https://www.getpagespeed.com/files/centos6-epel-eol.repo
ADD centos6-eol.repo centos6-epel-eol.repo /etc/yum.repos.d/
# From https://vault.epel.cloud/RPM-GPG-KEY-CentOS-6
# From https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-6
ADD RPM-GPG-KEY-CentOS-6 RPM-GPG-KEY-EPEL-6 /etc/pki/rpm-gpg/
RUN --mount=type=cache,sharing=private,target=/var/cache/yum \
    yum install --setopt=keepcache=1 --assumeyes rpm-build python34 glibc-devel libstdc++-devel gcc sudo
# Allow the bazelbuild user to install and erase RPM's when testing them
RUN echo "bazelbuild ALL = NOPASSWD: /bin/rpm *, /usr/bin/rpm *" > /etc/sudoers.d/bazelbuild
