FROM debian:11

RUN --mount=type=cache,sharing=private,target=/var/cache/apt \
    rm /etc/apt/apt.conf.d/docker-clean && \
    export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get install --assume-yes gcc libc6-dev python3
RUN getent group 100 | { IFS=: read group _ gid; groupdel $group; }