FROM centos:7

RUN --mount=type=cache,sharing=private,target=/var/cache/yum \
    yum install --setopt=keepcache=1 --assumeyes rpm-build python3 glibc-devel libstdc++-devel gcc sudo
# Allow the bazelbuild user to install and erase RPM's when testing them
RUN echo "bazelbuild ALL = NOPASSWD: /bin/rpm *, /usr/bin/rpm *" > /etc/sudoers.d/bazelbuild
