FROM ubuntu:focal

RUN --mount=type=cache,sharing=private,target=/var/cache/apt \
    export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get install --assume-yes gcc libc6-dev python3 sudo
# Allow the bazelbuild user to install and erase DEB's when testing them
RUN echo "bazelbuild ALL = NOPASSWD: /bin/dpkg *, /usr/bin/dpkg *" > /etc/sudoers.d/bazelbuild

