FROM rockylinux:9

RUN --mount=type=cache,sharing=private,target=/var/cache/yum \
    --mount=type=cache,sharing=private,target=/var/cache/dnf \
    yum install --setopt=keepcache=1 --assumeyes rpm-build python3 glibc-devel libstdc++-devel gcc sudo
# Allow the bazelbuild user to install and erase RPM's when testing them
RUN echo "bazelbuild ALL = NOPASSWD: /bin/rpm *, /usr/bin/rpm *" > /etc/sudoers.d/bazelbuild
RUN getent group 100 | while IFS=: read group _ gid; do groupdel --force ${group:?}; done
RUN getent passwd 1000 | while IFS=: read user _ uid; do userdel --remove ${user:?}; done
