FROM rockylinux:9

RUN --mount=type=cache,sharing=private,target=/var/cache/yum \
    --mount=type=cache,sharing=private,target=/var/cache/dnf \
    yum install --setopt=keepcache=1 --assumeyes rpm-build python3 glibc-devel libstdc++-devel gcc
RUN getent group 100 | { IFS=: read group _ gid; userdel games; groupdel $group; }
# Allow installation of RPM's in tests via sudo
RUN --mount=type=cache,sharing=private,target=/var/cache/yum \
    yum install --setopt=keepcache=1 --assumeyes sudo
# Allow the bazelbuild user to install and erase RPM's when testing them
RUN echo "bazelbuild ALL = NOPASSWD: /bin/rpm *, /usr/bin/rpm *" > /etc/sudoers.d/bazelbuild
